In [6]:
import requests
import pandas as pd
import numpy as np
from pprint import pprint

url = 'https://fantasy.premierleague.com/api/bootstrap-static/'

response = requests.get(url)
json = response.json()

In [5]:
events_df = pd.DataFrame(json["teams"])
events_df.head(20).sort_values("strength_overall_home", ascending= False)
events_df["strength_overall"] = (events_df["strength_overall_home"] + events_df["strength_overall_away"]) /2
events_df["strength_attack"] = (events_df["strength_attack_home"] + events_df["strength_attack_away"]) /2
events_df["strength_defence"] = (events_df["strength_defence_home"] + events_df["strength_defence_away"]) /2
teams = events_df[["name", "strength_overall", "strength_attack", "strength_defence"]]
teams.head(20).sort_values("strength_overall", ascending= False)

              name  strength_overall  strength_attack  strength_defence
11        Man City            1350.0           1300.0            1345.0
12         Man Utd            1285.0           1265.0            1275.0
5          Chelsea            1265.0           1280.0            1280.0
10       Liverpool            1255.0           1200.0            1265.0
0          Arsenal            1225.0           1140.0            1215.0
16           Spurs            1220.0           1150.0            1270.0
8        Leicester            1210.0           1170.0            1190.0
18        West Ham            1205.0           1165.0            1275.0
7          Everton            1190.0           1115.0            1170.0
9            Leeds            1165.0           1105.0            1190.0
1      Aston Villa            1130.0           1130.0            1090.0
3         Brighton            1115.0           1170.0            1115.0
19          Wolves            1095.0           1125.0            1080.0
6   Crystal Palace            1090.0           1075.0            1015.0
15     Southampton            1080.0           1070.0            1135.0
4          Burnley            1065.0           1065.0            1060.0
13       Newcastle            1060.0           1055.0            1070.0
14         Norwich            1025.0           1035.0            1025.0
17         Watford            1025.0           1040.0            1025.0
2        Brentford            1015.0           1025.0            1025.0

In [3]:
# url2 = 'https://fantasy.premierleague.com/api/fixures?event=1'

# r = requests.get(url2)
# json = r.json()
# json.keys()